import { Noto_Sans_JP } from 'next/font/google';

import type { Metadata } from 'next';
import './globals.css';

const inter = Noto_Sans_JP({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  team,
  analytics,
}: {
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div>{children}</div>
        <div>{team}</div>
        <div>{analytics}</div>
      </body>
    </html>
  );
}
